### ISSUE TITLE
Move qgc v3.x + to new repo

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#16]
Should we move the devel_v3 branch contents to a new repo for all v3.x + software development? The code is completely redone from v2.x to v3.x. And issues made on this repo for 2.x problems have no correlation to those made for 3.x problems.

E.g., fw_qgc_v3

**Comment by mantelt** [comment]
I'm totally neutral on this. I think it does not hurt to leave it in the current repo, but we would probably also not lose anything if we would create a new repo.

As the upstream repo anyway still has the full history, I guess we wouldn't gain a lot by creating a new repo. (And I would always put the full history in the new repo).

So after typing this lines, I notice that I'm leaning towards leaving it as is...

**Comment by philipoe** [comment]
I am rather strongly for leaving it as it is. It is still the same software, just another version, and git is designed _exactly_ for handling different versions of software in one repo. Otherwise, you could also move the current master of the Pixhawk firmware to a new repo because a lot of stuff is re-written.

Regarding the issues: I think that, as soon as we have moved to v3.x we should just close the old issues. By the way, @tstastny, please quickly recheck which of your issues are still relevant today i.e. for v2.3, seems like some of them may not apply anymore.

P.S: Just saw that you can assign "projects" to issues. So we could, during the time that we migrate to v3, mark all issues related to v3 with Project "QGC v3".

**Comment by tstastny** [comment]
ok. sounds fine. closing.
