### ISSUE TITLE
merging (some) of upstream

### ISSUE THREAD

**Issue by tstastny** [ethz-asl/qgc_asl#19]
I pushed 3 new branches. Each is branched from the one before it, with the original from devel_v3.

1) https://github.com/ethz-asl/fw_qgc/tree/feature_v3/merge_upstream_master

Merging upstream master into devel_v3 -> not all of it.. breaks at some point with some random things he is working on in the last days. Actually is much less buggy so far on the commit I merged in. Another nice thing is the "FW landing pattern" he added. We can directly use this for auto-landing w/o the matlab script I made before.

2) https://github.com/ethz-asl/fw_qgc/tree/feature_v3/add_circles

After merging upstream, I added nav wp and loiter wp circle visualization. Addresses #17 

3) https://github.com/ethz-asl/fw_qgc/tree/feature_v3/wp_additions

Approach type wp definitions + add a loiter radius to take-off wp.

These three branches (pulled in sequentially) will give us (almost) all QGC planning functionality we want for auto launch and land -- minus the take-off command I still need to put back in. But I think for review purposes it's better to keep each branches PR separate. Or at least keeping the upstream merge separate. Then I could also combine the other two (maybe even with the take-off button once it's there).

Issue made here to get your opinions on how I should proceed. This also effects how we merge in SatCom stuff @mhugentobler . As you would need to check if the upstream merge is okay for your stuff.

Thoughts?

[EDIT] I put links to the branches I was referring to @mhugentobler

**Comment by mhugentobler** [comment]
Since the fw landing pattern seems to be working nicely I will try to make satcom stuff work on that version as well. I hope they also fixed some other bugs since our devel_v3. If they didnt change everything again (as they did from v3.0 to v3.1) I think it shouldnt be too much trouble to  update satcom stuff from devel_v3 to current master, resp. the commit you merged in

**Comment by philipoe** [comment]
Just an info: If it helps you guys to make the current _devel_v3_ branch the current _master_ branch, then feel free to do that. It may be clearer for everyone what branch is being worked on at the moment (just saw that when looking at the branch-overview on github, all the branches say "4306 commits ahead of master", which looks a bit strange). However, before putting all the _devel_v3_ stuff into _master_ you'd then need to make a _stable_ branch from the current _master_ . I of course have nothing against keeping the current _devel_v3_-setup if you guys prefer that.

**Comment by tstastny** [comment]
@philipoe maybe we then make a "Stable_v2_3" branch? And then merge dev_v3 into master -- later can make a "Stable_v3_x" branch as we proceed. This anyway seems to be the drone community standard now. That master is for experimentation for releases.

**Comment by philipoe** [comment]
Mh, not sure what is best here. After all, at some point we don't need the stable_v2_3 branch anymore because we will have fully moved to QGC v3. So why not just make a "stable" branch based on 2.3 now, and then later on once our QGC v3 is actually stable release this as the new "stable" (while maybe tagging the old v2.3 stable appropriate such that it can be found in case of emergency)?

**Comment by tstastny** [comment]
Ok. Stable branch created. Tagged. Will make PRs now for master with v3.

**Comment by tstastny** [comment]
Ok - slight change in action: master replaced with devel_v3. stable = v2.3 (for now).
